language: java
git:
  quiet: true
branches:
  only:
    - master
before_install:
  - git submodule add https://github.com/integrated-evaluation-framework/IEvaluate-API.git
  - cd IEvaluate-API
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd ..
  - git submodule add https://github.com/integrated-evaluation-framework/IEvaluate-Core.git
  - cd IEvaluate-Core
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd ..